### ISSUE TITLE
Error in easy_select2.js

### ISSUE THREAD

**Issue by CleitonDeLima** [asyncee/django-easy-select2#60]
https://github.com/asyncee/django-easy-select2/blob/master/easy_select2/static/easy_select2/js/easy_select2.js#L114

`django.jQuery` not exists.

**Comment by gauravv7** [comment]
Hi Cleiton, which version of django are you using?

**Comment by CleitonDeLima** [comment]
Hi @gauravv7 , version 2.2.4

**Comment by gauravv7** [comment]
Hi @CleitonDeLima 

I have tried making a project with your django version, but I am not getting any error.
![screenshot](https://github.com/gauravv7/easy-select2/blob/master/issue_60.png?raw=true)


I must be due to some other theme/plugin you might be using. If you could share the project requirements/project itself, then I can try to debug and fix it.

Please find below link to my sample project. 
https://github.com/gauravv7/easy-select2

hope to help.

**Comment by CleitonDeLima** [comment]
Hi @gauravv7 

I not specifying that the error occurred outside of admin, sorry.

Apart from the `django.jQuery` admin does not exist, this is a detail that I ended up creating the `django` Object manually.

**Comment by gauravv7** [comment]
yes the object will be a manual attempt because custom template pages may not have it.
We can include jquery in the <head> as well.

I guess your issue is resolved then?

**Comment by gauravv7** [comment]
marked closed, due to no response.
